// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/categories": {
    params: {};
  };
  "/shop/:categoryId?": {
    params: {
      "categoryId"?: string;
    };
  };
  "/product/:slug": {
    params: {
      "slug": string;
    };
  };
  "/bundles": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/returns-policy": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/checkout/payment": {
    params: {};
  };
  "/checkout/confirmation": {
    params: {};
  };
  "/checkout/invoice": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/categories" | "/shop/:categoryId?" | "/product/:slug" | "/bundles" | "/cart" | "/returns-policy" | "/checkout" | "/checkout/payment" | "/checkout/confirmation" | "/checkout/invoice";
  };
  "components/layout/Layout.tsx": {
    id: "components/layout/Layout";
    page: "/" | "/categories" | "/shop/:categoryId?" | "/product/:slug" | "/bundles" | "/cart" | "/returns-policy";
  };
  "pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "pages/CategoriesGrid.tsx": {
    id: "pages/CategoriesGrid";
    page: "/categories";
  };
  "pages/ProductsListing.tsx": {
    id: "pages/ProductsListing";
    page: "/shop/:categoryId?";
  };
  "pages/ProductDetails.tsx": {
    id: "pages/ProductDetails";
    page: "/product/:slug";
  };
  "pages/BundlesListing.tsx": {
    id: "pages/BundlesListing";
    page: "/bundles";
  };
  "pages/Cart.tsx": {
    id: "pages/Cart";
    page: "/cart";
  };
  "pages/ReturnsPolicy.tsx": {
    id: "pages/ReturnsPolicy";
    page: "/returns-policy";
  };
  "pages/checkout/Shipping.tsx": {
    id: "pages/checkout/Shipping";
    page: "/checkout";
  };
  "pages/checkout/Payment.tsx": {
    id: "pages/checkout/Payment";
    page: "/checkout/payment";
  };
  "pages/checkout/Confirmation.tsx": {
    id: "pages/checkout/Confirmation";
    page: "/checkout/confirmation";
  };
  "pages/checkout/Invoice.tsx": {
    id: "pages/checkout/Invoice";
    page: "/checkout/invoice";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "components/layout/Layout": typeof import("./src/components/layout/Layout.tsx");
  "pages/Home": typeof import("./src/pages/Home.tsx");
  "pages/CategoriesGrid": typeof import("./src/pages/CategoriesGrid.tsx");
  "pages/ProductsListing": typeof import("./src/pages/ProductsListing.tsx");
  "pages/ProductDetails": typeof import("./src/pages/ProductDetails.tsx");
  "pages/BundlesListing": typeof import("./src/pages/BundlesListing.tsx");
  "pages/Cart": typeof import("./src/pages/Cart.tsx");
  "pages/ReturnsPolicy": typeof import("./src/pages/ReturnsPolicy.tsx");
  "pages/checkout/Shipping": typeof import("./src/pages/checkout/Shipping.tsx");
  "pages/checkout/Payment": typeof import("./src/pages/checkout/Payment.tsx");
  "pages/checkout/Confirmation": typeof import("./src/pages/checkout/Confirmation.tsx");
  "pages/checkout/Invoice": typeof import("./src/pages/checkout/Invoice.tsx");
};